Common methods, utility class implementetion (fixes #3)
sskorol/qaa-amazon pull request #4
Opened 2017-12-11 16:11 UTC by mkgerasimenko

- added common methods for base manipulations on page;
 - added utility class for mapping the `regexp` values to origin values;
 - added test for verify common methods;
 - added default value for regexp group into Base config;
 - added `ProductPage` object;
 - common refactoring.

2017-12-11 19:34 UTC, lmalakhova requested changes

2017-12-11 19:34 UTC, lmalakhova commented on src/test/resources/smoke-suite.xml
> -</suite>
Add new line

2017-12-11 19:45 UTC, lmalakhova approved these changes

2017-12-11 20:10 UTC, lmalakhova requested changes

2017-12-11 20:10 UTC, lmalakhova commented on src/test/java/io/github/sskorol/testcases/AmazonTests.java
>   * Tests for Google search page.
Change Javadoc  according to Test contents.

2017-12-12 08:55 UTC, mkgerasimenko commented on src/test/resources/smoke-suite.xml
> -</suite>
This is part has been removed.

2017-12-12 08:56 UTC, lmalakhova approved these changes

2017-12-12 08:59 UTC, merged